version: '3.8'

services:
  lmstudio:
    build: .
    container_name: lmstudio-api
    restart: unless-stopped
    
    # Solo puerto API
    ports:
      - "1234:1234"
    
    # Variables de entorno
    environment:
      - LMSTUDIO_HOST=0.0.0.0
      - LMSTUDIO_PORT=1234
      - LMSTUDIO_MODELS_PATH=/home/lmstudio/models
      - LMSTUDIO_DOMAIN=llm-api-llmapi.kutyaf.easypanel.host
      - LMS_SERVER_PORT=1234
      - LMS_API_PORT=1234
    
    # Volúmenes para modelos
    volumes:
      - lmstudio_models:/home/lmstudio/models
      - lmstudio_cache:/home/lmstudio/.cache/lm-studio
    
    # Recursos optimizados para CPU
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    
    # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1234/v1/models"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

# Volúmenes
volumes:
  lmstudio_models:
    driver: local
  lmstudio_cache:
    driver: local